Fix tpm2_checkquote when run on a big endian system
tpm2-software/tpm2-tools pull request #2228
Opened 2020-10-05 16:03 UTC by stefanberger

Various PCR related structures read by tpm2_checkquote are written
in little endian format, which needs to be taken into account when
run on a big endian system. Although little endian is unusual for
TPM, it is better to leave these data structure in little endian
format to not disrupt existing systems, so we do not convert these
structures to big endian on the side where they are written but
always read them as little endian.

Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

2020-10-06 16:07 UTC, stefanberger commented
I added a patch now that enforces that `tpm2_quote` writes its data in little endian format, which is not invasive for existing x86 systems. I have tested this now with `tpm2_quote` running on both big and little endian system and the `tpm2_checkquote` running on a big endian system.

2020-10-08 20:23 UTC, idesai requested changes

2020-10-08 20:23 UTC, idesai commented on lib/pcr.c
> +    // Loop through all PCR/hash banks
line comments to be used at end of line.
```suggestion
    /* Loop through all PCR/hash banks */
```

2020-10-08 20:23 UTC, idesai commented on lib/pcr.c
> +        // Loop through all PCRs in this bank
```suggestion
        /* Loop through all PCRs in this bank */
```

2020-10-08 20:23 UTC, idesai commented on lib/pcr.c
> +                continue;
```suggestion
                continue; //skip non-selected banks
```

2020-10-08 20:23 UTC, idesai commented on lib/pcr.c
> +            // Print out PCR ID
```suggestion
            /* Print out PCR ID */
```

2020-10-08 20:23 UTC, idesai commented on lib/pcr.c
> +            // Print out current PCR digest value
```suggestion
            /* Print out current PCR digest value */
```

2020-10-08 20:23 UTC, idesai commented on lib/systemdeps.h
> +/* SPDX-License-Identifier: BSD-3-Clause */
Please rename this file to tpm2_systemdeps.h

2020-10-08 20:23 UTC, idesai commented on lib/tpm2_openssl.c
> +// show all PCR banks according to g_pcrSelection & g_pcrs->
```suggestion
/* show all PCR banks according to g_pcrSelection & g_pcrs-> */
```

2020-10-08 20:23 UTC, idesai commented on lib/tpm2_openssl.c
> +    // Loop through all PCR/hash banks
```suggestion
    /* Loop through all PCR/hash banks */
```

2020-10-08 20:23 UTC, idesai commented on lib/tpm2_openssl.c
> +        // Loop through all PCRs in this bank
```suggestion
        /* Loop through all PCRs in this bank */
```

2020-10-08 20:23 UTC, idesai commented on lib/tpm2_openssl.c
> +                continue;
```suggestion
                continue; //skip non-selected banks
```

2020-10-08 20:23 UTC, idesai commented on lib/tpm2_openssl.c
> +            // Update running digest (to compare with quote)
```suggestion
            /* Update running digest (to compare with quote) */
```

2020-10-08 20:23 UTC, idesai commented on lib/tpm2_openssl.c
> +    // Finalize running digest
```suggestion
    /* Finalize running digest */
```

2020-10-08 20:23 UTC, idesai commented on tools/misc/tpm2_checkquote.c
> +#include "systemdeps.h"
```suggestion
#include "tpm2_systemdeps.h"
```

2020-10-14 21:08 UTC, idesai commented
- [ ] Test build with qemu-arm32v7

2020-10-14 21:15 UTC, merged