Verifying if digest matches event payload for certain event types
tpm2-software/tpm2-tools pull request #2264
Opened 2020-11-12 16:16 UTC by huang195

This PR attempts to verify eventlog entries by comparing digest values against payload, to thwart possible forgeries.

Relevant issues: Issue #2252, Issue #2247 

As I addressed in Issue #2252, verifying all event types is currently impossible from the eventlog alone. There are certain event types, e.g., EV_EFI_BOOT_SERVICES_APPLICATION, EV_EFI_BOOT_SERVICES_DRIVER, that are used to load driver, kernel, shim, grub code into the memory during the boot process, where their digest is calculated based on the loaded code, which is not included in the eventlog. There needs to be an out-of-band process to verify these events along with the in-band eventlog digest verification that we're doing here. Moreover, ambiguities in the spec could lead to vendor specific way of determining what data is used to calculate the digest. Also bugs in vendor firmware could also contribute to more variations. 

So, as a result, I felt that we should not fail-stop when digest verification fails, but simply print out warning messages and continue to parse the rest of the eventlog. Afterwards, another entity could take the warning messages and the parsed eventlog to further determine how to handle digest verification failure. 

This PR is currently only handling a few event types that we see consistent behaviors across different vendors. Once we have more understanding of other event types, their verification can be gradually added.

2020-11-13 19:07 UTC, huang195 commented
@idesai @williamcroberts  any idea why Travis is failing on only 1 of the 12 jobs? I looked at the failed tests, and it doesn't look like the PR should have an effect on them, but then again, I might be wrong. Any suggestions?

2020-11-16 18:41 UTC, idesai commented
> @idesai @williamcroberts any idea why Travis is failing on only 1 of the 12 jobs? I looked at the failed tests, and it doesn't look like the PR should have an effect on them, but then again, I might be wrong. Any suggestions?

I just had to re-run the specific build on travis.

2020-11-16 19:39 UTC, idesai requested changes

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +
```suggestion
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +
```suggestion
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            size_t alg_size = tpm2_alg_util_get_hash_size(alg);
```suggestion
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            size_t alg_size = tpm2_alg_util_get_hash_size(alg);
Define closest to its first use

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            if (memcmp(calc_digest.buffer, digest->Digest, alg_size) != 0) {
```suggestion

            size_t alg_size = tpm2_alg_util_get_hash_size(alg);
            if (memcmp(calc_digest.buffer, digest->Digest, alg_size) != 0) {
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            if (!tpm2_openssl_hash_compute_data(alg, event->Event, event->EventSize, &calc_digest)) {
```suggestion
            bool result = !tpm2_openssl_hash_compute_data(alg, event->Event,
            event->EventSize, &calc_digest);
            if (!result) {
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            if (!tpm2_openssl_hash_compute_data(alg, event->Event, event->EventSize, &calc_digest)) {
we don't hide a function return in a conditional statement.

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +                LOG_WARN("Event %lu's digest does not match its payload", eventnum-1);
```suggestion
                LOG_WARN("Event %lu's digest does not match its payload",
                eventnum - 1);
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            digest = (TCG_DIGEST2*)((uintptr_t)digest->Digest + alg_size);
```suggestion

            digest = (TCG_DIGEST2*)((uintptr_t)digest->Digest + alg_size);
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +
```suggestion
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +
```suggestion
        if (eventhdr->PCRIndex == 9) {
            return true;
        }

```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +
```suggestion
        if (eventhdr->PCRIndex == 14) {
            return true;
        }

```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            TPM2B_DIGEST calc_digest;
```suggestion
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            TPM2B_DIGEST calc_digest;
Define closest to first use

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            }
```suggestion
            }

```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            if (j+1 >= event->EventSize || event->Event[event->EventSize-1] != '\0') {
```suggestion
            if (j + 1 >= event->EventSize || event->Event[event->EventSize - 1] != '\0') {
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +                LOG_WARN("Event %lu's event data is in unexpected format", eventnum-1);
```suggestion
                LOG_WARN("Event %lu's event data is in unexpected format", eventnum - 1);
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            if (!tpm2_openssl_hash_compute_data(alg, event->Event+j+1, event->EventSize-j-2, &calc_digest)) {
```suggestion
            TPM2B_DIGEST calc_digest;
            TPMI_ALG_HASH alg = digest->AlgorithmId;
            bool result = tpm2_openssl_hash_compute_data(alg,
            event->Event + (j + 1), event->EventSize - (j - 2), &calc_digest);
            if (!result) {
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +                LOG_WARN("Event %lu: Cannot calculate hash value from data", eventnum-1);
```suggestion
                LOG_WARN("Event %lu: Cannot calculate hash value from data", eventnum - 1);
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +            if (memcmp(calc_digest.buffer, digest->Digest, alg_size) != 0) {
```suggestion

            size_t alg_size = tpm2_alg_util_get_hash_size(alg);
            if (memcmp(calc_digest.buffer, digest->Digest, alg_size) != 0) {
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +                LOG_WARN("Event %lu's digest does not match its payload", eventnum-1);
```suggestion
                LOG_WARN("Event %lu's digest does not match its payload", eventnum - 1);
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +        return true;
```suggestion
```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
> +
```suggestion
        if (ctx->data != 0) {
            verify_digests(*(size_t*)ctx->data, eventhdr, event);
        }

```

2020-11-16 19:39 UTC, idesai commented on lib/tpm2_eventlog.c
>  #include <tss2/tss2_tpm2_types.h>
```suggestion

#include <tss2/tss2_tpm2_types.h>
```

2020-11-16 19:41 UTC, idesai commented
@huang195 if this is a new eventype being parsed,  I'd appreciate you add the eventlog binary to our test fixtures. Thank you for this PR.

2020-11-16 19:56 UTC, huang195 commented
@idesai all the event types this PR checks are already included in one or more of the existing test fixtures. BTW, is there a particular formatter you're using as I could run that through before submitting PRs in the future. Thanks!

2020-11-16 20:02 UTC, idesai commented
> @idesai all the event types this PR checks are already included in one or more of the existing test fixtures. BTW, is there a particular formatter you're using as I could run that through before submitting PRs in the future. Thanks!

@williamcroberts has one for eclipse [here](https://github.com/tpm2-software/tpm2-tools/blob/5505dc9893406ba6297f3b1711616f5ee5687760/misc/formatters/tpm2.0-eclipse-cdt-formatter.xml)

2020-11-16 21:31 UTC, idesai commented
@huang195 please rebase these to a single commit.

2020-11-16 21:54 UTC, huang195 commented
@idesai squashed to a single commit

2020-11-16 22:03 UTC, idesai approved these changes

2020-11-17 14:37 UTC, williamcroberts commented
> > @idesai @williamcroberts any idea why Travis is failing on only 1 of the 12 jobs? I looked at the failed tests, and it doesn't look like the PR should have an effect on them, but then again, I might be wrong. Any suggestions?
> 
> I just had to re-run the specific build on travis.

Looks like:
```
spawn tss2 sign --keyPath=HS/SRK/mySignKey --padding=RSA_PSS --digest=/tmp/tpm2_test_bqnEzM/tss2_fapi.i9ewEy/digest.file --signature=/tmp/tpm2_test_bqnEzM/tss2_fapi.i9ewEy/signature.file --publicKey=/tmp/tpm2_test_bqnEzM/tss2_fapi.i9ewEy/public_key.file
ERROR:fapi:src/tss2-fapi/ifapi_policy_callbacks.c:907:search_policy() ErrorCode (0x0006002e) Policy not found. 
ERROR:fapi:src/tss2-fapi/ifapi_policy_callbacks.c:1191:ifapi_exec_auth_policy() ErrorCode (0x0006002e) Search policy 
ERROR:fapi:src/tss2-fapi/ifapi_policy_execute.c:614:execute_policy_authorize() Execute authorized policy. ErrorCode (0x0006002e) 
ERROR:fapi:src/tss2-fapi/ifapi_policy_execute.c:1526:execute_policy_element() ErrorCode (0x0006002e) Execute policy authorize 
ERROR:fapi:src/tss2-fapi/ifapi_policy_execute.c:1736:ifapi_policyeval_execute() Execute policy. ErrorCode (0x0006002e) 
ERROR:fapi:src/tss2-fapi/ifapi_policyutil_execute.c:320:ifapi_policyutil_execute() Execute policy. ErrorCode (0x0006002e) 
WARNING:esys:src/tss2-esys/api/Esys_FlushContext.c:234:Esys_FlushContext_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:89:Esys_FlushContext() Esys Finish ErrorCode (0x000001c4) 
ERROR:fapi:src/tss2-fapi/fapi_util.c:2042:ifapi_authorize_object() Execute policy. ErrorCode (0x0006002e) 
ERROR:fapi:src/tss2-fapi/fapi_util.c:2737:ifapi_key_sign() ErrorCode (0x0006002e) Authorize signature key. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Sign.c:299:Fapi_Sign_Finish() Fapi sign. ErrorCode (0x0006002e) 
ERROR:esys:src/tss2-esys/esys_iutil.c:1101:esys_GetResourceObject() Error: Esys handle does not exist (70018). 
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:138:Esys_FlushContext_Async() flushHandle unknown. ErrorCode (0x00070018) 
ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:66:Esys_FlushContext() Error in async function ErrorCode (0x00070018) 
ERROR:fapi:src/tss2-fapi/api/Fapi_Sign.c:130:Fapi_Sign() ErrorCode (0x0006002e) Key_Sign 
Fapi_Sign(0x6002E) - fapi:The policy is unknown
The system has not asked for branch selection
```

I don't know why Fapi Sign would start failing.... @AndreasFuchsSIT did something break in the TSS libraries?

2020-11-17 14:40 UTC, williamcroberts commented
Is it related to https://github.com/tpm2-software/tpm2-tools/pull/2262?

2020-11-17 16:13 UTC, huang195 commented
@williamcroberts my other PR is also failing at exactly the same places as this one, but failures don't seem to be relevant to the PRs.

2020-11-18 09:40 UTC, cplappert commented
The issue is addressed in #2268.

2020-11-24 14:23 UTC, williamcroberts commented
@huang195 can you rebase on top of master and force push your branch, the CI should be working again.

2020-11-24 16:22 UTC, huang195 commented
@williamcroberts rebased, but I'm not sure what the error means. Can you please advise?

2020-11-24 16:22 UTC, huang195 commented
@williamcroberts rebased, but I'm not sure what the error means. Can you please advise?

2020-11-24 17:31 UTC, williamcroberts commented
> @williamcroberts rebased, but I'm not sure what the error means. Can you please advise?

I just re-triggered cirrus, lets see if it resolves.

2020-11-25 02:22 UTC, huang195 commented
@williamcroberts yep, looks that did the trick

2020-11-30 19:16 UTC, williamcroberts commented
Tested here:
https://github.com/williamcroberts/tpm2.0-tools/actions/runs/392273641

Merging.

2020-11-30 19:16 UTC, merged