feat: support to sign and verify of the sm2 algorithms.
tpm2-software/tpm2-tools pull request #2923
Opened 2022-01-21 06:55 UTC by ymj-uos

Signed-off-by: 杨明君 <yangmingjun@uniontech.com>

2022-01-21 06:58 UTC, ymj-uos commented
rm -v -f -r temp/

mkdir temp

cd temp

export TPM2TOOLS_TCTI=device:/dev/tpm0

tpm2 flushcontext -T device:/dev/tpm0 -t
tpm2 flushcontext -T device:/dev/tpm0 -l
tpm2 flushcontext -T device:/dev/tpm0 -s

# echo -n "b2e14c5c79c6df5b85f4fe7ed8db7a262b9da7e07ccb0ea9f4747b8ccda8a4f3" | xxd -r -ps > plaintext_signing.hex
echo -n "message digest" > plaintext_signing.hex

tpm2 loadexternal -Q -C n -G sm2 -u ../standard_data/SM2-PubKey-GMT0003_5-2012.pem -c key_external.ctx

# xxd -g 4 -c 32 plaintext_signing.hex
# xxd -g 4 -c 32 ../standard_data/SM2-Demo-Signed-GMT0003_5-2012.hex

tpm2 verifysignature -c key_external.ctx -g sm3_256 -m plaintext_signing.hex  -f sm2 -s ../standard_data/SM2-Demo-Signed-GMT0003_5-2012.hex

tpm2 flushcontext -T device:/dev/tpm0 -t

tpm2 loadexternal -Q -C n -G sm2 -r ../standard_data/SM2-PriKey-GMT0003_5-2012.pem -c key_pair_external.ctx

# tpm2 readpublic -c key_pair_external.ctx -o sm2.fmt.pub --format=pem
# openssl ec -noout -text -inform PEM -in sm2.fmt.pub -pubin

tpm2 sign -c key_pair_external.ctx -s sm2 -g sm3_256 -f plain -o sig.4 plaintext_signing.hex 

# need the upper versions of openssl 1.1.1d.5
openssl dgst -sm3 \
            -verify ../standard_data/SM2-PubKey-GMT0003_5-2012.pem \
            -signature sig.4 \
            plaintext_signing.hex

openssl dgst -sm3 \
            -sign ../standard_data/SM2-PriKey-GMT0003_5-2012.pem \
            -out sig.5 \
            plaintext_signing.hex

tpm2 verifysignature -c key_pair_external.ctx -g sm3_256 -m plaintext_signing.hex -f sm2 -s sig.5
tpm2 flushcontext -T device:/dev/tpm0 -t

tpm2 createprimary -Q -C e -g sm3_256 -G sm2 -c primary.ctx
tpm2 create -Q -g sm3_256 -G sm2 -u key-pair.pub -r key-pair.priv -C primary.ctx
tpm2 flushcontext -T device:/dev/tpm0 -t

tpm2 load -Q -C primary.ctx -u key-pair.pub -r key-pair.priv -n name.load.B1_B8 -c key-pair.ctx
tpm2 readpublic -Q -c key-pair.ctx -o tpm2.sm2.pub.pem --format=pem
# openssl ec -noout -text -inform PEM -in tpm2.sm2.pub.pem -pubin
tpm2 flushcontext -T device:/dev/tpm0 -t

tpm2 sign -c key-pair.ctx -s sm2 -g sm3_256 -f plain -o sig.6 plaintext_signing.hex
openssl dgst -sm3 \
            -verify tpm2.sm2.pub.pem \
            -signature sig.6 \
            plaintext_signing.hex

chmod a+r -R .
chown uos:uos -R .

ls -l
exit 0

I use this script to check the result of TPM calculate. all of which are correct.

2022-01-21 07:13 UTC, ymj-uos commented
[Uploading GMT.0003.2-2012.SM2-en.pdf.pdf…]()
[Uploading GMT.0003.5-2012.SM2-en.pdf.pdf…]()

2022-01-21 07:20 UTC, ymj-uos commented
![image](https://user-images.githubusercontent.com/75604505/150483702-5034e073-70ce-49cf-a3c8-8ed4665f346b.png)

@idesai 《TCG_TPM2_r1p59_Part1_Architecture_pub》

2022-01-25 18:44 UTC, idesai requested changes

2022-01-26 01:47 UTC, ymj-uos commented on lib/tpm2_alg_util.c
> +    size = 2 + sizeof(id) + sizeof(a) + sizeof(b) + sizeof(gx) + sizeof(gy) +
2 is size of variable 'ebytes'

2022-01-26 17:56 UTC, idesai commented on lib/tpm2_alg_util.c
> +    rc = tpm2_readpublic(ectx, tr_handle, &public, 0, 0);
```suggestion
     TPM2B_PUBLIC *public = 0;
     tool_rc rc = tpm2_readpublic(ectx, tr_handle, &public, 0, 0);
```

2022-01-26 18:45 UTC, merged