WIP - CI Multiarch
tpm2-software/tpm2-tools pull request #3110
Opened 2022-08-09 23:04 UTC by malikabhi05

2022-08-16 00:24 UTC, idesai commented
@JuergenReppSIT can you please comment on the failures in fapi tests seen [here](https://github.com/tpm2-software/tpm2-tools/runs/7796693036?check_suite_focus=true#step:5:238).

2022-08-16 21:09 UTC, malikabhi05 commented on test/integration/helpers.sh
> +                                       --seccomp action="none" \
@idesai

2022-08-16 21:35 UTC, idesai commented
> @malikabhi05 @idesai Could you please run the tss2_provisioning of one fapi test e.g. fapi-get-random.sh with:
> 
> ```
> ls -l */* >&2
> TSS2_LOG=fapi+trace tss2_provision
> ```
> 
> The profile, which was not found, should be written to the tmp directory of the test and listed by the ls command. The part of the log to find the profile should be similar to:
> 
> ```
> trace:fapi:src/tss2-fapi/ifapi_io.c:489:ifapi_io_dirfiles() List directory: /tmp/tpm2_test_ux0guC/tss2_fapi.KWILpL/
> ...
> trace:fapi:src/tss2-fapi/ifapi_io.c:502:ifapi_io_dirfiles() Looking at P_ECCP256SHA256.json 
> ```

This is on the failing build

trace:fapi:src/tss2-fapi/ifapi_io.c:489:ifapi_io_dirfiles() List directory: /tmp/tpm2_test_W77OAn/tss2_fapi.JEKMv5/ 
ERROR:fapi:src/tss2-fapi/ifapi_profiles.c:116:ifapi_profiles_initialize_async() No files found in profile dir /tmp/tpm2_test_W77OAn/tss2_fapi.JEKMv5/ that match the pattern P_*.json 
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:283:Fapi_Initialize_Finish() Read profile ErrorCode (0x0006000b) 
trace:fapi:src/tss2-fapi/api/Fapi_Initialize.c:85:Fapi_Initialize() finished 
Fapi_Initialize(0x6000B) - fapi:A parameter has a bad value
TSS2_LOG=fapi+trace tss2_provision on line 21 failed: 1
ERROR:fapi:src/tss2-fapi/ifapi_profiles.c:116:ifapi_profiles_initialize_async() No files found in profile dir /tmp/tpm2_test_W77OAn/tss2_fapi.JEKMv5/ that match the pattern P_*.json 
ERROR:fapi:src/tss2-fapi/api/Fapi_Initialize.c:283:Fapi_Initialize_Finish() Read profile ErrorCode (0x0006000b) 
Fapi_Initialize(0x6000B) - fapi:A parameter has a bad value
FAIL test/integration/fapi/fapi-get-random.sh (exit status: 1)

2022-08-16 21:43 UTC, malikabhi05 commented
@JuergenReppSIT we're seeing this on a 32 bit container "ubuntu-20.04.arm32v7"

2022-08-17 16:49 UTC, malikabhi05 commented on test/integration/helpers.sh
> +                                       --seccomp action="none" \
@williamcroberts @idesai should I only disable seccomp for multi arch builds or for all builds?

2022-08-17 17:24 UTC, williamcroberts commented on test/integration/helpers.sh
> +                                       --seccomp action="none" \
All builds is fine

2022-08-18 17:16 UTC, malikabhi05 commented
load test will pass once #3112 is updated and merged.

2022-08-26 19:13 UTC, idesai commented on Makefile.am
> +test_unit_test_object_LDFLAGS = -Wl,--wrap=tpm2_util_object_fetch_tssprivkey_from_file
```suggestion
```

2022-08-26 19:14 UTC, idesai commented on test/unit/test_object.c
> +tool_rc __wrap_tpm2_util_object_fetch_tssprivkey_from_file(const char *objectstr,
```suggestion
tool_rc tpm2_util_object_fetch_tssprivkey_from_file(const char *objectstr,
```

2022-08-26 19:15 UTC, idesai commented on test/unit/test_object.c
> +        unsigned char address[] = {0x7e, 0xe0, 0x00, 0x01};
Use ASN1_Integer_set routines like so in **tpm2_encodeobject**

2022-08-26 19:15 UTC, idesai commented on test/unit/test_object.c
> +}
```suggestion
}

```

2022-08-26 19:16 UTC, idesai commented on lib/object.c
> +    tool_rc rct = tpm2_util_object_fetch_tssprivkey_from_file(objectstr, &input_bio, &tpk);
```suggestion
rc = tpm2_util_object_fetch_tssprivkey_from_file(objectstr, &input_bio, &tpk);

2022-08-26 19:17 UTC, idesai commented on test/unit/test_object.c
> +
```suggestion
```

2022-08-26 19:18 UTC, idesai commented on test/unit/test_object.c
> +
```suggestion
```

2022-08-29 22:58 UTC, idesai requested changes

2022-08-29 22:58 UTC, idesai commented on test/integration/tests/encodeobject.sh
> +-o $pem_file.pem
$Pem_persistent_parent instead of 0x81100000?

2022-08-29 22:58 UTC, idesai commented on test/integration/tests/encodeobject.sh
> +  # negative parent exists
```suggestion
  # negative parent exists
  echo "Fail: Parent value is negative"
```

2022-08-29 22:58 UTC, idesai commented on test/integration/tests/encodeobject.sh
> +  exit 0
```suggestion
```

2022-08-29 22:58 UTC, idesai commented on test/integration/tests/encodeobject.sh
> +
```suggestion

exit 0

```

2022-08-30 13:24 UTC, idesai requested changes

2022-08-30 13:24 UTC, idesai commented on .github/workflows/main.yml
> +          malikabhi05/test-ac/runCI@master
```suggestion
          tpm2-software/ci/runCI@main
```

2022-08-31 14:29 UTC, idesai commented
One small change:
[ci: point CI to correct CI repo](https://github.com/tpm2-software/tpm2-tools/pull/3110/commits/060c4283e2b3f3b9bc60a11cb8277d4b4a156044) must be merged into [Adding multiarch var](https://github.com/tpm2-software/tpm2-tools/pull/3110/commits/6a1c53204a9b769baaf564894b5d10df1acba80c)
The fix in the last commit is for a bug in the same PR.

2022-09-06 19:05 UTC, merged