Skip test_tpm2_header tests in BE architectures
tpm2-software/tpm2-tools pull request #3184
Opened 2023-01-05 13:36 UTC by aplanas

The tests are casting a fixed stream of bytes into a struct.  This array is already expressed in little endian order, so big endian processors will fail the test (PPC, PPC64, S390X, for example)

This commit skip the test in those architectures

Signed-off-by: Alberto Planas <aplanas@suse.com>

2023-04-13 11:36 UTC, JuergenReppSIT requested changes
see last comment.

2023-12-20 21:19 UTC, williamcroberts commented on test/unit/test_tpm2_header.c
>      assert_true(c->tag == 0x0180);
It's really that the bytestream is in big endian as thats what the TPM produces and the checks on the scalars in the struct being casted on it are gonna be weird based on byte ordering. I guess this test was to ensure that `tpm2_command_header_from_bytes` didn't modify anything, which I guess means that:
1. tpm2_command_header_from_bytes should take a const pointer `const UINT8 *`.
2. These tests could be removed as the compiler won't allow modification.

I can spin these up real quick.

2023-12-20 21:31 UTC, williamcroberts commented
@aplanas could you test my fix is on #3323, it should fix it and we can drop this PR.

2023-12-20 22:15 UTC, williamcroberts commented
Closing in favor of #3323

2023-12-20 22:15 UTC, closed without merging