tpm2_getekcertificate: add support to high range NV indexes
tpm2-software/tpm2-tools pull request #3440
Opened 2024-12-09 23:04 UTC by loicsikidi

Fixes #3435.

_Note_:

* The test case uses self-signed certificates because I didn't found a valid one in `https://ekop.intel.com` (e.g. RSA 3072 or ECC P384)

2024-12-11 09:27 UTC, JuergenReppSIT commented
@loicsikidi your PR would change the behaviour of `tpm2_getekcertificate` for TPMs with certificates in the low and in the high range (e.g. Infineon SLB 9672). Instead of the low range certificates the high range certificates would be saved.
It would be better to implement the option `-u pubkey` which currently can't be used for certificates in the NV ram.

2024-12-12 11:45 UTC, JuergenReppSIT requested changes
If you would change the lookup part as follows:
```
    ctx.rsa_ek_cert_nv_location = 0xffffffff;
    ctx.ecc_ek_cert_nv_location = 0xffffffff;

    for (i = 0; i < capability_data->data.handles.count; i++) {
        TPMI_RH_NV_INDEX index = capability_data->data.handles.handle[i];
        const ek_index_map *m = lookup_ek_index_map(index);
        if (!m) {
            continue;
        }

        if (m->key_type == KTYPE_RSA && index < ctx.rsa_ek_cert_nv_location) {
            LOG_INFO("Found pre-provisioned RSA EK certificate at %u [type=%s]", index, m->name);
            ctx.is_rsa_ek_cert_nv_location_defined = true;
            ctx.rsa_ek_cert_nv_location = m->index;
        }
        if (m->key_type == KTYPE_ECC && index < ctx.ecc_ek_cert_nv_location) {
            LOG_INFO("Found pre-provisioned ECC EK certificate at %u [type=%s]", index, m->name);
            ctx.is_ecc_ek_cert_nv_location_defined = true;
            ctx.ecc_ek_cert_nv_location = m->index;
        }
    }
```
it's ensured  that the certificate would be written as previously. The high range certificates would only be written if no low level certificates exist. After your PR is merges I would add a PR with the -u option to enable saving the EK certificate based on the public EK.
I think that's an better solution than allowing e.g. four -o options to save all certificates.

2024-12-12 23:02 UTC, loicsikidi commented
@JuergenReppSIT I've added your suggestion and one more test to attest that *if there are >= 2 certs of the same type => the low range one must be returned.*

Thanks for the feedback!

I wasn't aware that some TPMs have more than one EK cert from the same family :sweat_smile:

2024-12-13 08:05 UTC, JuergenReppSIT approved these changes
@loicsikidi Thank you for the PR. I have already prepared the -u change.

2024-12-13 10:20 UTC, loicsikidi commented
@JuergenReppSIT I think that I've found the issue :bulb: .

The last test is failing because there are 2 "eligible" EK certs in NVRAM but there is only one `-o`... 

```bash
## Make sure that if there are several certificates of the same type, then the one belonging to low range has priority
openssl x509 -in ecc_ek_cert.bin -out ecc_low_range_ek_cert.der -outform DER
define_ek_cert_nv_index ecc_low_range_ek_cert.der $ECC_EK_CERT_NV_INDEX

tpm2 getekcertificate -o nv_ecc_ek_cert.der

diff nv_ecc_ek_cert.der ecc_low_range_ek_cert.der
```

ERROR:

> WARN: Found 2 certficates on NV. Add another -o to save the ECC cert

My bad..., I'll push a fix :rocket:

2024-12-13 10:50 UTC, loicsikidi commented
I think that we can retry :muscle:

2024-12-14 10:14 UTC, merged

2024-12-14 10:14 UTC, JuergenReppSIT commented
@loicsikidi Thank you for the fix.